# Generated by Django 3.2.8 on 2022-01-17 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='loves',
            field=models.ManyToManyField(related_name='blog_posts_loves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='blog_post_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
